apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "vigo-bus-core.fullname" . }}-token'
  labels:
    {{- include "vigo-bus-core.labels" . | nindent 4 }}
stringData:
  api-token: "{{ .Values.apiToken }}"
  google-maps-api-key: "{{ .Values.googleMapsAPIKey }}"