apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "vigo-bus-tg-bot.fullname" . }}-token'
  labels:
    {{- include "vigo-bus-tg-bot.labels" . | nindent 4 }}
stringData:
  bot-token: "{{ .Values.botToken }}"
  api-token: "{{ .Values.apiToken }}"