name: Package and Upload Helm Chart

on:
  workflow_dispatch:

jobs:
  package-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3.5 # v3.5
        with:
          version: v3.15.2
      - name: Install Helm Push Plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Find and build Helm charts
        run: |
          set -e
          charts=$(find . -name 'Chart.yaml')
          for chart in $charts; do
            chart_dir=$(dirname $chart)
            echo "Downloading dependencies for $chart_dir"
            helm dependency update $chart_dir
            echo "Building chart in $chart_dir"
            helm package $chart_dir
          done

      - name: Push Helm charts to Harbor
        run: |
          set -e
          charts=$(find . -name '*.tgz')
          for chart in $charts; do
            helm push $chart oci://ghcr.io/${{ github.repository }}
          done
